### Variables
@baseUrl = http://localhost:3000
@contentType = application/json

@authToken = 

@userId = 

@noteId = 

### Create a new note
POST {{baseUrl}}/notes
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "My First Note",
  "content": "This is the content of my first note."
}

### Get all notes
GET {{baseUrl}}/notes
Authorization: Bearer {{authToken}}

### Get a specific note by ID
GET {{baseUrl}}/notes/{{noteId}}
Authorization: Bearer {{authToken}}

### Update a note
PATCH {{baseUrl}}/notes/{{noteId}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "title": "My Updated Note",
  "content": "This is the updated content of my first note."
}

### Delete a note
DELETE {{baseUrl}}/notes/{{noteId}}
Authorization: Bearer {{authToken}}

### Try to get deleted note
GET {{baseUrl}}/notes/{{noteId}}
Authorization: Bearer {{authToken}}

