### author Tests
@baseUrl = http://localhost:3000/authors
@contentType = application/json

### Get all authors 
GET {{baseUrl}}

### Add an author
POST {{baseUrl}}
Content-Type: {{contentType}}

{
    "name": "Jane Mukuru",
    "biography": "English novelist known for her six major novels.",
    "birthDate": "1975-12-16"
}

### Get one author
GET {{baseUrl}}/Geo33

### Get author by name
GET {{baseUrl}}/search/Elly Lee


### Update an author
PUT {{baseUrl}}/At021
Content-Type: {{contentType}}

{
    "biography": "Award Winning Novist.",
    "birthDate": "1985-12-16"
}

### Delete an author
DELETE {{baseUrl}}/Zx132