### Variables
@baseUrl = http://localhost:3000
@contentType = application/json

### Create a new note
POST {{baseUrl}}/notes
Content-Type: {{contentType}}

{
  "title": "Meeting Notes",
  "content": "Discussed project timeline and deliverables. Next meeting scheduled for next week."
}


### Get all notes
GET {{baseUrl}}/notes


### Get a specific note by ID 
GET {{baseUrl}}/notes/1


### Update a note
PATCH {{baseUrl}}/notes/1
Content-Type: {{contentType}}

{
  "title": "My Updated First Note"
}

### Delete a note
DELETE {{baseUrl}}/notes/1

###

### Try to get deleted note 
GET {{baseUrl}}/notes/1


